import { StyleSheet } from 'react-native'

export enum COLOR {
    defaultBackground = '#F5F5F5', //Background color for components, also used for buttons text
    main = '#002667',
    secondary = '#005555',
    tertiary = '#54BAB9',
    backgroundDarker = '#c6c6c6',
    text = '#202020',
    hilight = '#069A8E',
    disable = '#b5b5b5',
    backgroundUnfocused = '#00000080',
    backgroundFocused = '#00000020',
}
const backgroundImage = require('../assets/background.png')
const honeywellLogo = require('../assets/logo.png')

export default StyleSheet.create({
    backgroundImage: backgroundImage,
    honeywellLogo: honeywellLogo,
    versao: {
        fontSize: 14,
        color: COLOR.disable,
    },
    container: {
        flex: 1,
        //1marginBottom: '5%',
        marginTop: 2,
    },
    background: {
        flex: 1,
        flexDirection: 'row',
        height: '100%',
        justifyContent: 'center',
        position: 'absolute',
        resizeMode: 'cover',
        width: '100%',
    },
    btn: {
        backgroundColor: COLOR.hilight,
        marginVertical: '3%',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 10,
        flexDirection: 'row',
        display: 'flex',
        overflow: 'hidden',
        minHeight: '2%',
        minWidth: '8%',
    },
    btnDarker: {
        backgroundColor: COLOR.secondary,
        marginVertical: '3%',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 10,
        flexDirection: 'row',
        display: 'flex',
        overflow: 'hidden',
        minHeight: '2%',
        minWidth: '8%',
    },
    btnLight: {
        backgroundColor: COLOR.tertiary,
        marginVertical: '3%',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 10,
        flexDirection: 'row',
        display: 'flex',
        overflow: 'hidden',
        minHeight: '2%',
        minWidth: '8%',
    },
    listaLinhas: {
        marginTop: '2%',
        marginBottom: '2%',
        backgroundColor: '#cecece',
        padding: '4%',
        borderRadius: 10,
    },
    listaLinhasUnmarked: {
        marginTop: '2%',
        marginBottom: '2%',
        backgroundColor: '#cecece',
        width: '100%',
        padding: '4%',
        borderRadius: 10,
    },
    listaLinhasMarked: {
        marginTop: '2%',
        marginBottom: '2%',
        backgroundColor: '#1274b7',
        width: '100%',
        padding: '4%',
        borderRadius: 10,
    },
    btnScan: {
        flex: 1,
        backgroundColor: '#EFCA08',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 0,
        flexDirection: 'row',
        display: 'flex',
        overflow: 'hidden',
        minHeight: '10%',
        minWidth: '10%',
    },
    input: {
        backgroundColor: '#FEFEFE',
        borderWidth: 2,
        height: 37,
        borderColor: COLOR.text,
        marginBottom: '2%',
        color: '#222',
        fontSize: 17,
        borderRadius: 10,
        padding: 5,
        maxWidth: '90%',
        minWidth: '70%',
    },
    inputGeneric: {
        backgroundColor: '#FEFEFE',
        borderWidth: 0.5,
        borderColor: '#1274b7',
        height: 37,
        marginBottom: '2%',
        color: '#222',
        fontSize: 17,
        borderRadius: 10,
        padding: 10,
        textAlign: 'center',
    },
    dropDown: {
        backgroundColor: '#FEFEFE',
        borderWidth: 0.5,
        borderColor: '#1274b7',
        width: '90%',
        height: 40,
        marginBottom: '2%',
        color: '#222',
        fontSize: 20,
        borderRadius: 10,
        padding: 10,
        marginLeft: '1%',
        maxWidth: '100%',
        minWidth: '98%',
    },
    viewFather: {
        flexDirection: 'column',
        marginHorizontal: '2%',
    },
    buttonIcon: {
        height: '90%',
        width: '20%',
        backgroundColor: 'rgba(0, 0, 0, 0.1)',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 10,
    },
    titulo: {
        width: '100%',
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'left',
        borderBottomWidth: 3,
        borderColor: '#1274B7',
        borderTopWidth: 1,
        borderTopColor: '#AAA',
        marginTop: 2,
        padding: 10,
    },
    qtdBox: {
        fontSize: 40,
        borderColor: '#1274B7',
        borderRadius: 10,
        borderWidth: 2,
        width: '50%',
        textAlign: 'center',
        padding: 10,
        marginTop: 5,
    },
    bigBox: {
        fontSize: 20,
        borderColor: '#1274B7',
        borderRadius: 10,
        borderWidth: 2,
        width: '98%',
        textAlign: 'center',
        padding: 10,
        marginTop: 5,
    },
    crumb: {
        backgroundColor: '#FFF',
        borderWidth: 0,
        flex: 0,
    },
    crumbAtivo: {
        backgroundColor: '#1274B7',
    },
    crumbContainer: {
        backgroundColor: '#FFF',
        borderWidth: 0,
    },
    filterBtn: {
        display: 'flex',
        flex: 1,
        borderRadius: 5,
        margin: 5,
        padding: 3,
        borderWidth: 2,
        borderColor: '#000',
        borderStyle: 'solid',
    },
    filterMarker: {
        display: 'flex',
        flex: 1,
        backgroundColor: '#000',
        marginLeft: 2,
        marginRight: 2,
    },
    modal: {
        backgroundColor: '#DDDDDD',
        borderRadius: 5,
        borderColor: '#1274B7',
        borderWidth: 1,
    },
    iconeMenu: {
        alignItems: 'center',
        backgroundColor: '#FFF',
        borderRadius: 40,
        height: 35,
        margin: 3,
        paddingTop: 1,
    },
    buttonExit: {
        fontSize: 18,
        justifyContent: 'center',
        height: 25,
        width: 25,
        textAlign: 'center',
    },
    btnMenu: {
        backgroundColor: COLOR.backgroundDarker,
        marginVertical: '3%',
        alignItems: 'center',
        justifyContent: 'flex-start',
        borderRadius: 10,
        flexDirection: 'row',
        display: 'flex',
        overflow: 'hidden',
        minHeight: '2%',
        minWidth: '8%',
        height: 40,
        margin: 5,
    },
    iconMenu: {
        backgroundColor: COLOR.secondary,
        borderTopRightRadius: 25,
        borderBottomRightRadius: 25,
        borderTopLeftRadius: 10,
        borderBottomLeftRadius: 10,
        width: 50,
        height: 40,
        paddingStart: 5,
        flexDirection: 'row',
        alignItems: 'center',
    },
    textMenu: {
        color: COLOR.text,
        left: 10,
        fontSize: 20,
    },
    menuTitle: {
        fontSize: 30,
        color: COLOR.secondary,
        fontWeight: 'bold',
        lineHeight: 35,
    },
    modalConfig: {
        left: '5%',
        width: '80%',
        borderRadius: 10,
        backgroundColor: COLOR.defaultBackground,
    },
    containerModal: {
        flexDirection: 'column',
        justifyContent: 'center',
        alignContent: 'center',
        height: '90%',
        padding: 10,
    },
    text: {
        fontSize: 18,
        color: COLOR.text,
        lineHeight: 40,
    },
    containerAlocarInput: {
        backgroundColor: COLOR.backgroundDarker,
        height: 145,
        borderRadius: 10,
    },

    textInput: {
        backgroundColor: COLOR.defaultBackground,
        color: COLOR.text,
        fontSize: 18,
        lineHeight: 18,
        height: 40,
        width: '80%',
        marginLeft: 10,
        borderColor: '#858585',
        borderRadius: 10,
        borderWidth: 2,
        marginTop: 15,
    },
    textInputTransparent: {
        color: '#fff',
        fontSize: 16,
        borderBottomColor: '#FFFFFF90',
        borderBottomWidth: 2,
        paddingBottom: 2,
    },
    iconInput: {
        color: COLOR.secondary,
        marginTop: 18,
        marginLeft: 10,
    },
    backBtn: {
        height: 60,
        top: 20,
        alignContent: 'center',
        flexDirection: 'row',
        display: 'flex',
        justifyContent: 'flex-start',
    },
    mainContainer: {
        // flexDirection: 'column',
        // justifyContent: 'center',
        // alignContent: 'center',
        // textAlignVertical: 'top',
        height: '95%',
        margin: 15,
        marginTop: 20,
    },
})
